# Generated by Django 2.2 on 2020-08-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='variant',
            field=models.CharField(max_length=300, verbose_name='Варианты ответов'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания вопроса'),
        ),
    ]
