# Generated by Django 2.2 on 2020-08-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200829_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='variant',
            field=models.TextField(max_length=300, verbose_name='Варианты ответов'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(max_length=300, verbose_name='Вопрос'),
        ),
    ]
